apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-route
  namespace: my-first-model
  labels:
    app: llama-stack
spec:
  to:
    kind: Service
    name: lsd-llama-milvus-inline-service
    weight: 100
  port:
    targetPort: 8321
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

