apiVersion: v1
kind: Secret
metadata:
  name: milvus-secret
  namespace: my-first-model
type: Opaque
stringData:
  MILVUS_ENDPOINT: "tcp://milvus-service:19530"
  MILVUS_TOKEN: "<milvus-root-or-user-token>"
  MILVUS_CONSISTENCY_LEVEL: "Bounded"

